### ISSUE TITLE
RStudio-server installation script

### ISSUE THREAD

**Issue by ck37** [ucberkeley/bce#58] opened 2015-07-24 05:06 UTC
It would be nice if we provided a simple RStudio-server installation script. It's a very handy service that I think a lot of people may use, although maybe not worth auto-enabling by default.

The commands are essentially:

``` bash
wget https://download2.rstudio.org/rstudio-server-0.99.467-amd64.deb
sudo gdebi rstudio-server-0.99.467-amd64.deb
sudo adduser rstudio
```
- The adduser will generate a password for the rstudio user. Maybe we could/should use oski instead?
- The latest .deb is posted at https://www.rstudio.com/products/rstudio/download-server/

I will try to implement this sometime if someone doesn't beat me to it.

And in theory, we might be able to use instance meta-data (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) so that people can add a tag for "rstudio-server" when creating the instance so that the script runs without requiring an ssh and manual execution. Not sure how to implement that yet though.

**Comment by cboettig** [comment] 2015-07-24 17:42
You can also take a look at the recipe we use in the rocker project: https://github.com/rocker-org/rocker/blob/master/rstudio/Dockerfile

Minor differences -- we query RStudio's data to look up which is the latest version, and we symlink the pandoc binaries installed by RStudio.  We found having separate installations of pandoc in and outside of rstudio could lead to unexpected behavior due to version differences, etc when using rmarkdown functions in and out of RStudio.  (also, I think `adduser` will prompt for info unless you include some other arguments? Note that you cannot just do `useradd` instead because RStudio server will fail to launch if it cannot find a home directory for the user.  Of course using `oski` would probably sidestep these issues).  

Also just thought I'd note that we had to get permission from RStudio to distribute their product packaged with other software in binary form (e.g. an image or container) to meet with their trademark rules.  They were very nice and accommodating about this and maybe that's already been taken care of for BCE.

**Comment by paciorek** [comment] 2015-07-25 16:18
Chris, if you do create the script, please link to it from
http://bce.berkeley.edu/downloads.html, where there are some other add-on
scripts to add functionality to BCE.

**Comment by aculich** [comment] 2015-10-02 17:37
@aculich will handle the non-technical issues
@ryanlovett will handle the technical issues

**Comment by cboettig** [comment] 2015-10-13 20:44
Just tested this on the Fall-2015 release and it is working rather nicely!

Perhaps you would consider adding `/usr/lib/rstudio-server/bin/:` into the `PATH` so it can be launched with just `rserver`?

**Comment by ryanlovett** [comment] 2015-10-14 20:28
Technical issue fixed by 4546ff85ad116a02708fd174cda64e6af38cc904.

Ryan

**Comment by paciorek** [comment] 2016-04-14 21:55
I'm trying this out now using fall-2015 and having an issue with having the
rstudio-server processes launch. I think there should be an 'rserver'
process running but it's not.

Any ideas?

ubuntu@ip-172-31-24-188:~$ sudo rstudio-server status
● rstudio-server.service - RStudio Server
   Loaded: loaded (/etc/systemd/system/rstudio-server.service; enabled;
vendor preset: enabled)
   Active: active (running) since Thu 2016-04-14 21:50:51 UTC; 11s ago
  Process: 3066 ExecStop=/usr/bin/killall -TERM rserver (code=exited,
status=0/SUCCESS)
  Process: 3081 ExecStart=/usr/lib/rstudio-server/bin/rserver (code=exited,
status=0/SUCCESS)
 Main PID: 3082 (rserver)
   CGroup: /system.slice/rstudio-server.service
           └─3082 /usr/lib/rstudio-server/bin/rserver

Apr 14 21:50:51 ip-172-31-24-188 systemd[1]: Starting RStudio Server...
Apr 14 21:50:51 ip-172-31-24-188 systemd[1]: Started RStudio Server.
ubuntu@ip-172-31-24-188:~$ sudo rstudio-server verify-installation
ubuntu@ip-172-31-24-188:~$ ps aux | grep rstudio
rstudio+  3158  0.4  0.6 192452  6884 ?        Ssl  21:51   0:00
/usr/lib/rstudio-server/bin/rserver
ubuntu    3180  0.0  0.2   8212  2108 pts/8    S+   21:51   0:00 grep
--color=auto rstudio
ubuntu@ip-172-31-24-188:~$ sudo rstudio-server stop
rsession: no process found

**Comment by cboettig** [comment] 2016-04-14 22:07
@paciorek What you show looks good to me, though I haven't tested the BCE script recently.  I believe the reason you're seeing `rsession: no process found` is because you haven't yet logged into the RStudio instance in the browser.  (e.g. I get matching output to what you show above if I just use launch the rocker/rstudio docker image and exec into it.  Once I log in through the browser, `rstudio-server stop` restarts the `rsession` instead of erroring with `no process found`

**Comment by paciorek** [comment] 2016-04-14 22:31
Hmm, well, when I try to log on via the browser, the browser window
immediately hangs and gives nothing back.

Also, I hadn't realized it until just now but it looks like rstudio-server
is already installed in BCE-2015-fall. When I start a brand new instance
and do not try to install the rstudio-server .deb and then check on the
rstudio-server process status, things are as I previously described.

**Comment by paciorek** [comment] 2016-04-15 00:18
Never mind, I think it's just that I forgot to tell the instance to open
the port.

**Comment by paciorek** [comment] 2016-05-26 20:48
I believe we now provide rstudio-server.

**Closed as completed by paciorek** 2016-05-26 20:48 UTC
Labels: enhancement, software request
